version: '3.3'

services:
  jenkins:
    build: #TODO: Once plugin installation is handled through c-as-c this can be removed and replaced with 'image'.
      context: ./master
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    secrets:
      - github  #Github username with password as an example.
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml #Use a github repo.  Be aware that the raw content is cached, so it can take a couple of minutes to take effect
secrets: #Be careful with newlines in your secrets, make sure to remove them before running docker-compose up.
  github:
    file: /var/deploy/secrets/github
volumes:
  jenkins_home:
